# -*- coding: utf-8 -*-
"""Untitled59.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cROoMYfpm1GBS1OCEFyWmoCrwlXEbwu
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint


j_true = 50.0
j_nominal = 42.0
lam = 2.2
k_gain = 25.0
phi = 0.08
dt = 0.01
t_end = 15.0
t_span = np.arange(0, t_end, dt)

def atmospheric_torque(t):

    return (5 + 2*t) * np.sin(0.5 * t**2) + np.random.normal(0, 0.5)

def smc_dynamics(state, t, j_val, target):
    theta, omega = state
    theta_d, dot_theta_d, ddot_theta_d = target, 0.0, 0.0


    e = theta - theta_d
    de = omega - dot_theta_d


    s = de + lam * e


    u_eq = j_nominal * (ddot_theta_d - lam * de)


    sat_s = np.clip(s / phi, -1, 1)
    u_rob = -k_gain * sat_s

    u = u_eq + u_rob


    dist = atmospheric_torque(t)
    d_omega = (u + dist) / j_true
    d_theta = omega

    return [d_theta, d_omega], u, s, dist


states = []
u_history = []
s_history = []
dist_history = []
current_state = [1.5, 0.5]

for t in t_span:

    derivs, u, s, d = smc_dynamics(current_state, t, j_true, 0.0)
    states.append(current_state)
    u_history.append(u)
    s_history.append(s)
    dist_history.append(d)


    current_state = [current_state[0] + derivs[0]*dt,
                     current_state[1] + derivs[1]*dt]

states = np.array(states)


fig = plt.figure(figsize=(16, 10), facecolor='white')

# Plot 1: Tracking Performance
ax1 = plt.subplot(2, 2, 1)
ax1.plot(t_span, states[:, 0], 'b', lw=2.5, label='Actual Angle')
ax1.axhline(0, color='r', ls='--', label='Target')
ax1.set_title('Satellite Orientation Tracking', fontsize=14, fontweight='bold')
ax1.grid(True, alpha=0.3); ax1.legend()

# Plot 2: Phase Portrait (The "Sliding" visualization)
ax2 = plt.subplot(2, 2, 2)
ax2.plot(states[:, 0], states[:, 1], 'g', lw=2)
# Draw the Sliding Surface Line: de = -lam * e
x_vals = np.linspace(min(states[:, 0]), max(states[:, 0]), 100)
ax2.plot(x_vals, -lam * x_vals, 'r--', alpha=0.6, label='Sliding Surface (S=0)')
ax2.set_xlabel('Error (e)'); ax2.set_ylabel('Error Rate (de)')
ax2.set_title('Phase Plane: The "Sliding" Action', fontsize=14, fontweight='bold')
ax2.grid(True, alpha=0.3); ax2.legend()

# Plot 3: Control Input (Actuator Effort)
ax3 = plt.subplot(2, 2, 3)
ax3.plot(t_span, u_history, 'm', lw=1.5)
ax3.set_title('Robust Control Input (Reaction Wheel Torque)', fontsize=14, fontweight='bold')
ax3.set_ylabel('Torque [Nm]'); ax3.grid(True, alpha=0.3)

# Plot 4: Robustness Analysis (Disturbance Rejection)
ax4 = plt.subplot(2, 2, 4)
ax4.plot(t_span, dist_history, 'k', alpha=0.4, label='Atmospheric Disturbance')
ax4.plot(t_span, s_history, 'r', lw=2, label='Sliding Surface (s)')
ax4.set_title('Surface Stability vs. Disturbance', fontsize=14, fontweight='bold')
ax4.legend(); ax4.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("--- ANALYTICAL INFERENCE ---")
print(f"Tracking converged to {states[-1,0]:.5f} rad despite 16% Model Uncertainty.")
print(f"Peak Disturbance Handled: {max(dist_history):.2f} Nm.")